apiVersion: v1
kind: Service
metadata:
  labels:
    app: event-api
  name: event-api
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 3333
  selector:
    app: event-api
  type: LoadBalancer
status:
  loadBalancer: {}